package com.openhabbo.communication.headers;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import com.openhabbo.api.communication.headers.MessageHeaderProvider;
import com.openhabbo.communication.events.advertisement.GetInterstitialMessageEvent;
import com.openhabbo.communication.events.advertisement.GetRoomAdMessageEvent;
import com.openhabbo.communication.events.avatar.ChangeUserNameMessageEvent;
import com.openhabbo.communication.events.avatar.CheckUserNameMessageEvent;
import com.openhabbo.communication.events.avatar.GetWardrobeMessageEvent;
import com.openhabbo.communication.events.avatar.SaveWardrobeOutfitMessageEvent;
import com.openhabbo.communication.events.catalog.*;
import com.openhabbo.communication.events.facebook.FaceBookInitiateAddFriendsMessageEvent;
import com.openhabbo.communication.events.facebook.FaceBookIsLoggedOffMessageEvent;
import com.openhabbo.communication.events.facebook.FaceBookIsLoggedOnMessageEvent;
import com.openhabbo.communication.events.friendlist.*;
import com.openhabbo.communication.events.handshake.*;
import com.openhabbo.communication.events.help.*;
import com.openhabbo.communication.events.inventory.achievements.GetAchievementsMessageEvent;
import com.openhabbo.communication.events.inventory.avatareffect.AvatarEffectActivatedMessageEvent;
import com.openhabbo.communication.events.inventory.avatareffect.AvatarEffectSelectedMessageEvent;
import com.openhabbo.communication.events.inventory.badges.GetBadgePointLimitsMessageEvent;
import com.openhabbo.communication.events.inventory.badges.GetBadgesMessageEvent;
import com.openhabbo.communication.events.inventory.badges.SetActivatedBadgesMessageEvent;
import com.openhabbo.communication.events.inventory.furni.RequestFurniInventoryMessageEvent;
import com.openhabbo.communication.events.inventory.furni.RequestRoomPropertySetMessageEvent;
import com.openhabbo.communication.events.inventory.pets.GetPetInventoryMessageEvent;
import com.openhabbo.communication.events.inventory.purse.GetCreditsInfoMessageEvent;
import com.openhabbo.communication.events.inventory.trading.*;
import com.openhabbo.communication.events.marketplace.*;
import com.openhabbo.communication.events.moderator.*;
import com.openhabbo.communication.events.navigator.*;
import com.openhabbo.communication.events.notifications.ResetUnseenItemsMessageEvent;
import com.openhabbo.communication.events.poll.PollAnswerMessageEvent;
import com.openhabbo.communication.events.poll.PollRejectMessageEvent;
import com.openhabbo.communication.events.poll.PollStartMessageEvent;
import com.openhabbo.communication.events.poll.VoteAnswerMessageEvent;
import com.openhabbo.communication.events.quest.*;
import com.openhabbo.communication.events.recycler.GetRecyclerPrizesMessageEvent;
import com.openhabbo.communication.events.recycler.GetRecyclerStatusMessageEvent;
import com.openhabbo.communication.events.recycler.RecycleItemsMessageEvent;
import com.openhabbo.communication.events.register.UpdateFigureDataMessageEvent;
import com.openhabbo.communication.events.room.action.*;
import com.openhabbo.communication.events.room.avatar.*;
import com.openhabbo.communication.events.room.chat.*;
import com.openhabbo.communication.events.room.engine.*;
import com.openhabbo.communication.events.room.furniture.*;
import com.openhabbo.communication.events.room.pets.GetPetInfoMessageEvent;
import com.openhabbo.communication.events.room.pets.RespectPetMessageEvent;
import com.openhabbo.communication.events.room.publicroom.ChangeRoomMessageEvent;
import com.openhabbo.communication.events.room.publicroom.ExitLockerRoomMessageEvent;
import com.openhabbo.communication.events.room.publicroom.TryBusMessageEvent;
import com.openhabbo.communication.events.room.session.*;
import com.openhabbo.communication.events.roomsettings.DeleteRoomMessageEvent;
import com.openhabbo.communication.events.roomsettings.GetRoomSettingsMessageEvent;
import com.openhabbo.communication.events.roomsettings.SaveRoomSettingsMessageEvent;
import com.openhabbo.communication.events.sound.*;
import com.openhabbo.communication.events.tracking.*;
import com.openhabbo.communication.events.userdefinedroomevents.*;
import com.openhabbo.communication.events.users.*;

import java.util.HashMap;

public class DefaultMessageHeaderProvider implements MessageHeaderProvider {

    private final BiMap eventClasses = HashBiMap.create(new HashMap<Class, Short>() {{
        put(InitCryptoMessageEvent.class, (short) 206);
        put(GenerateSecretKeyMessageEvent.class, (short) 2002);
        put(VersionCheckMessageEvent.class, (short) 1170);
        put(UniqueIDMessageEvent.class, (short) 813);
        put(GetSessionParametersMessageEvent.class, (short) 1817);
        put(SSOTicketMessageEvent.class, (short) 415);
        put(TryLoginMessageEvent.class, (short) 756);
        put(PongMessageEvent.class, (short) 196);
        put(InfoRetrieveMessageEvent.class, (short) 7);
        put(DisconnectMessageEvent.class, (short) 0x0200);
        put(MessengerInitMessageEvent.class, (short) 12);
        put(FriendListUpdateMessageEvent.class, (short) 15);
        put(SendMsgMessageEvent.class, (short) 33);
        put(AcceptBuddyMessageEvent.class, (short) 37);
        put(DeclineBuddyMessageEvent.class, (short) 38);
        put(RequestBuddyMessageEvent.class, (short) 39);
        put(RemoveBuddyMessageEvent.class, (short) 40);
        put(HabboSearchMessageEvent.class, (short) 41);
        put(GetBuddyRequestsMessageEvent.class, (short) 233);
        put(FollowFriendMessageEvent.class, (short) 262);
        put(SendRoomInviteMessageEvent.class, (short) 34);
        put(FindNewFriendsMessageEvent.class, (short) 490);
        put(GetEventStreamMessageEvent.class, (short) 500);
        put(SetEventStreamingAllowedMessageEvent.class, (short) 501);
        put(GetCreditsInfoMessageEvent.class, (short) 8);
        put(RequestRoomPropertySetMessageEvent.class, (short) 66);
        put(RequestFurniInventoryMessageEvent.class, (short) 404);
        put(AvatarEffectSelectedMessageEvent.class, (short) 372);
        put(AvatarEffectActivatedMessageEvent.class, (short) 373);
        put(GetBadgesMessageEvent.class, (short) 157);
        put(SetActivatedBadgesMessageEvent.class, (short) 158);
        put(GetBadgePointLimitsMessageEvent.class, (short) 3032);
        put(GetAchievementsMessageEvent.class, (short) 370);
        put(UnacceptTradingMessageEvent.class, (short) 68);
        put(AcceptTradingMessageEvent.class, (short) 69);
        put(CloseTradingMessageEvent.class, (short) 70);
        put(OpenTradingMessageEvent.class, (short) 71);
        put(AddItemToTradeMessageEvent.class, (short) 72);
        put(ConfirmAcceptTradingMessageEvent.class, (short) 402);
        put(ConfirmDeclineTradingMessageEvent.class, (short) 403);
        put(RemoveItemFromTradeMessageEvent.class, (short) 405);
        put(GetPetInventoryMessageEvent.class, (short) 3000);
        put(MakeOfferMessageEvent.class, (short) 3010);
        put(GetMarketplaceConfigurationMessageEvent.class, (short) 3011);
        put(GetMarketplaceCanMakeOfferMessageEvent.class, (short) 3012);
        put(BuyMarketplaceTokensMessageEvent.class, (short) 3013);
        put(BuyOfferMessageEvent.class, (short) 3014);
        put(CancelOfferMessageEvent.class, (short) 3015);
        put(RedeemOfferCreditsMessageEvent.class, (short) 3016);
        put(GetOffersMessageEvent.class, (short) 3018);
        put(GetOwnOffersMessageEvent.class, (short) 3019);
        put(GetMarketplaceItemStatsMessageEvent.class, (short) 3020);
        put(DeleteFavouriteRoomMessageEvent.class, (short) 20);
        put(AddFavouriteRoomMessageEvent.class, (short) 19);
        put(GetUserFlatCatsMessageEvent.class, (short) 151);
        put(CanCreateEventMessageEvent.class, (short) 345);
        put(CreateEventMessageEvent.class, (short) 346);
        put(CancelEventMessageEvent.class, (short) 347);
        put(EditEventMessageEvent.class, (short) 348);
        put(GetRoomSettingsMessageEvent.class, (short) 400);
        put(SaveRoomSettingsMessageEvent.class, (short) 401);
        put(DeleteRoomMessageEvent.class, (short) 23);
        put(GetOfficialRoomsMessageEvent.class, (short) 380);
        put(GetPopularRoomTagsMessageEvent.class, (short) 382);
        put(UpdateNavigatorSettingsMessageEvent.class, (short) 384);
        put(GetGuestRoomMessageEvent.class, (short) 385);
        put(UpdateRoomThumbnailMessageEvent.class, (short) 386);
        put(CanCreateRoomMessageEvent.class, (short) 387);
        put(CreateFlatMessageEvent.class, (short) 29);
        put(RateFlatMessageEvent.class, (short) 261);
        put(GetPublicSpaceCastLibsMessageEvent.class, (short) 388);
        put(PopularRoomsSearchMessageEvent.class, (short) 430);
        put(RoomsWithHighestScoreSearchMessageEvent.class, (short) 431);
        put(MyFriendsRoomsSearchMessageEvent.class, (short) 432);
        put(RoomsWhereMyFriendsAreSearchMessageEvent.class, (short) 433);
        put(MyRoomsSearchMessageEvent.class, (short) 434);
        put(MyFavouriteRoomsSearchMessageEvent.class, (short) 435);
        put(MyRoomHistorySearchMessageEvent.class, (short) 436);
        put(RoomTextSearchMessageEvent.class, (short) 437);
        put(RoomTagSearchMessageEvent.class, (short) 438);
        put(LatestEventsSearchMessageEvent.class, (short) 439);
        put(ToggleStaffPickMessageEvent.class, (short) 483);
        put(GetPetCommandsMessageEvent.class, (short) 3004);
        put(OpenConnectionMessageEvent.class, (short) 2);
        put(OpenFlatConnectionMessageEvent.class, (short) 391);
        put(ChatMessageEvent.class, (short) 52);
        put(ShoutMessageEvent.class, (short) 55);
        put(WhisperMessageEvent.class, (short) 56);
        put(StartTypingMessageEvent.class, (short) 317);
        put(CancelTypingMessageEvent.class, (short) 318);
        put(SignMessageEvent.class, (short) 104);
        put(ChangeMottoMessageEvent.class, (short) 484);
        put(GoToFlatMessageEvent.class, (short) 59);
        put(GetRoomEntryDataMessageEvent.class, (short) 390);
        put(UseFurnitureMessageEvent.class, (short) 392);
        put(PickupObjectMessageEvent.class, (short) 67);
        put(MoveObjectMessageEvent.class, (short) 73);
        put(SetObjectDataMessageEvent.class, (short) 74);
        put(MoveAvatarMessageEvent.class, (short) 75);
        put(PlaceObjectMessageEvent.class, (short) 90);
        put(MoveWallItemMessageEvent.class, (short) 91);
        put(PlacePetMessageEvent.class, (short) 3002);
        put(RemovePetFromFlatMessageEvent.class, (short) 3003);
        put(ViralTeaserFoundMessageEvent.class, (short) 3103);
        put(GetMOTDMessageEvent.class, (short) 3110);
        put(GetUserNotificationsMessageEvent.class, (short) 3105);
        put(ChangeQueueMessageEvent.class, (short) 211);
        put(RoomDimmerGetPresetsMessageEvent.class, (short) 341);
        put(RoomDimmerSavePresetMessageEvent.class, (short) 342);
        put(RoomDimmerChangeStateMessageEvent.class, (short) 343);
        put(UseWallItemMessageEvent.class, (short) 393);
        put(GetItemDataMessageEvent.class, (short) 83);
        put(SetItemDataMessageEvent.class, (short) 84);
        put(RemoveItemMessageEvent.class, (short) 85);
        put(ViralFurniStatusMessageEvent.class, (short) 3104);
        put(GetPetInfoMessageEvent.class, (short) 3001);
        put(GetFurnitureAliasesMessageEvent.class, (short) 215);
        put(QuitMessageEvent.class, (short) 53);
        put(PlacePostItMessageEvent.class, (short) 3254);
        put(AddSpamWallPostItMessageEvent.class, (short) 3255);
        put(DanceMessageEvent.class, (short) 93);
        put(WaveMessageEvent.class, (short) 94);
        put(LookToMessageEvent.class, (short) 79);
        put(ThrowDiceMessageEvent.class, (short) 76);
        put(DiceOffMessageEvent.class, (short) 77);
        put(PresentOpenMessageEvent.class, (short) 78);
        put(CreditFurniRedeemMessageEvent.class, (short) 183);
        put(EnterOneWayDoorMessageEvent.class, (short) 232);
        put(SpinWheelOfFortuneMessageEvent.class, (short) 247);
        put(SetRandomStateMessageEvent.class, (short) 314);
        put(SetClothingChangeDataMessageEvent.class, (short) 480);
        put(QuestVendingWallItemMessageEvent.class, (short) 3100);
        put(OpenPetPackageMessageEvent.class, (short) 3006);
        put(OpenWelcomeGiftMessageEvent.class, (short) 3252);
        put(KickUserMessageEvent.class, (short) 95);
        put(AssignRightsMessageEvent.class, (short) 96);
        put(RemoveRightsMessageEvent.class, (short) 97);
        put(LetUserInMessageEvent.class, (short) 98);
        put(RemoveAllRightsMessageEvent.class, (short) 155);
        put(BanUserMessageEvent.class, (short) 320);
        put(CallGuideBotMessageEvent.class, (short) 440);
        put(KickBotMessageEvent.class, (short) 441);
        put(GetUserTagsMessageEvent.class, (short) 263);
        put(GetSelectedBadgesMessageEvent.class, (short) 159);
        put(GetHabboGroupBadgesMessageEvent.class, (short) 230);
        put(GetHabboGroupDetailsMessageEvent.class, (short) 231);
        put(IgnoreUserMessageEvent.class, (short) 319);
        put(GetIgnoredUsersMessageEvent.class, (short) 321);
        put(UnignoreUserMessageEvent.class, (short) 322);
        put(RespectUserMessageEvent.class, (short) 371);
        put(RespectPetMessageEvent.class, (short) 3005);
        put(PickIssuesMessageEvent.class, (short) 450);
        put(ReleaseIssuesMessageEvent.class, (short) 451);
        put(CloseIssuesMessageEvent.class, (short) 452);
        put(GetModeratorUserInfoMessageEvent.class, (short) 454);
        put(GetUserChatlogMessageEvent.class, (short) 455);
        put(GetRoomChatlogMessageEvent.class, (short) 456);
        put(GetCfhChatlogMessageEvent.class, (short) 457);
        put(GetRoomVisitsMessageEvent.class, (short) 458);
        put(GetModeratorRoomInfoMessageEvent.class, (short) 459);
        put(ModerateRoomMessageEvent.class, (short) 460);
        put(ModAlertMessageEvent.class, (short) 461);
        put(ModMessageMessageEvent.class, (short) 462);
        put(ModKickMessageEvent.class, (short) 463);
        put(ModBanMessageEvent.class, (short) 464);
        put(ModeratorActionMessageEvent.class, (short) 200);
        put(CallForHelpMessageEvent.class, (short) 453);
        put(GetPendingCallsForHelpMessageEvent.class, (short) 237);
        put(DeletePendingCallsForHelpMessageEvent.class, (short) 238);
        put(GetClientFaqsMessageEvent.class, (short) 416);
        put(GetFaqCategoriesMessageEvent.class, (short) 417);
        put(GetFaqTextMessageEvent.class, (short) 418);
        put(SearchFaqsMessageEvent.class, (short) 419);
        put(GetFaqCategoryMessageEvent.class, (short) 420);
        put(ChangeEmailMessageEvent.class, (short) 3253);
        put(ScrGetUserInfoMessageEvent.class, (short) 26);
        put(GetAchievementShareIdMessageEvent.class, (short) 481);
        put(ResetUnseenItemsMessageEvent.class, (short) 3111);
        put(PurchaseFromCatalogMessageEvent.class, (short) 100);
        put(PurchaseFromCatalogAsGiftMessageEvent.class, (short) 472);
        put(GetGiftWrappingConfigurationMessageEvent.class, (short) 473);
        put(GetClubGiftInfoMessageEvent.class, (short) 474);
        put(SelectClubGiftMessageEvent.class, (short) 475);
        put(GetCatalogIndexMessageEvent.class, (short) 101);
        put(GetCatalogPageMessageEvent.class, (short) 102);
        put(RedeemVoucherMessageEvent.class, (short) 129);
        put(GetIsOfferGiftableMessageEvent.class, (short) 3030);
        put(GetClubOffersMessageEvent.class, (short) 3031);
        put(GetSellablePetBreedsMessageEvent.class, (short) 3007);
        put(MarkCatalogNewAdditionsPageOpenedMessageEvent.class, (short) 3034);
        put(GetHabboClubExtendOfferMessageEvent.class, (short) 3035);
        put(PurchaseVipMembershipExtensionMessageEvent.class, (short) 3036);
        put(PurchaseBasicMembershipExtensionMessageEvent.class, (short) 3037);
        put(GetHabboBasicMembershipExtendOfferMessageEvent.class, (short) 3038);
        put(GetRecyclerPrizesMessageEvent.class, (short) 412);
        put(GetRecyclerStatusMessageEvent.class, (short) 413);
        put(RecycleItemsMessageEvent.class, (short) 414);
        put(GetRoomAdMessageEvent.class, (short) 126);
        put(GetInterstitialMessageEvent.class, (short) 182);
        put(LatencyPingRequestMessageEvent.class, (short) 315);
        put(LatencyPingReportMessageEvent.class, (short) 316);
        put(PerformanceLogMessageEvent.class, (short) 421);
        put(LagWarningReportMessageEvent.class, (short) 422);
        put(EventLogMessageEvent.class, (short) 482);
        put(VoteAnswerMessageEvent.class, (short) 112);
        put(PollRejectMessageEvent.class, (short) 235);
        put(PollStartMessageEvent.class, (short) 234);
        put(PollAnswerMessageEvent.class, (short) 236);
        put(ExitLockerRoomMessageEvent.class, (short) 108);
        put(ChangeRoomMessageEvent.class, (short) 111);
        put(TryBusMessageEvent.class, (short) 113);
        put(ApproveNameMessageEvent.class, (short) 42);
        put(GetSoundMachinePlayListMessageEvent.class, (short) 245);
        put(GetNowPlayingMessageEvent.class, (short) 249);
        put(GetSongInfoMessageEvent.class, (short) 221);
        put(GetSoundSettingsMessageEvent.class, (short) 228);
        put(SetSoundSettingsMessageEvent.class, (short) 229);
        put(AddJukeboxDiskMessageEvent.class, (short) 0xFF);
        put(RemoveJukeboxDiskMessageEvent.class, (short) 0x0100);
        put(GetJukeboxPlayListMessageEvent.class, (short) 258);
        put(GetUserSongDisksMessageEvent.class, (short) 259);
        put(GetWardrobeMessageEvent.class, (short) 375);
        put(SaveWardrobeOutfitMessageEvent.class, (short) 376);
        put(ChangeUserNameMessageEvent.class, (short) 470);
        put(CheckUserNameMessageEvent.class, (short) 471);
        put(UpdateFigureDataMessageEvent.class, (short) 44);
        put(UpdateTriggerMessageEvent.class, (short) 3050);
        put(UpdateActionMessageEvent.class, (short) 3051);
        put(UpdateConditionMessageEvent.class, (short) 3052);
        put(OpenMessageEvent.class, (short) 3053);
        put(ApplySnapshotMessageEvent.class, (short) 3054);
        put(GetQuestsMessageEvent.class, (short) 3101);
        put(AcceptQuestMessageEvent.class, (short) 3102);
        put(RejectQuestMessageEvent.class, (short) 3106);
        put(OpenQuestTrackerMessageEvent.class, (short) 3107);
        put(StartCampaignMessageEvent.class, (short) 3108);
        put(FriendRequestQuestCompleteMessageEvent.class, (short) 3210);
        put(FaceBookIsLoggedOnMessageEvent.class, (short) 3300);
        put(FaceBookIsLoggedOffMessageEvent.class, (short) 3301);
        put(FaceBookInitiateAddFriendsMessageEvent.class, (short) 3311);
    }});

    public DefaultMessageHeaderProvider() {
        // TODO: Load the headers from a XML file or something.
    }

    @Override
    public short getHeaderByEventClass(Class eventClass) {
        if (this.eventClasses.containsKey(eventClass)) {
            return (short) this.eventClasses.get(eventClass);
        }

        return -4000;
    }

    @Override
    public short getHeaderByComposerClass(Class composerClass) {
        return 0;
    }

    @Override
    public Class getEventClassByHeader(short header) {
        return (Class) this.eventClasses.inverse().get(header);
    }

    @Override
    public Class getComposerClassByHeader(short header) {
        return null;
    }
}
